server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

kafka:
  bootstrapAddress: localhost:9092

message:
  topic:
    name: baeldung
greeting:
  topic:
    name: greeting
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned